@host = http://localhost:3000
@urlMovies = /api/movies
@urlCharacters = /api/characters

@urlUsers = /api/users





####### Movies
GET {{host}}{{urlMovies}}

###

GET {{host}}{{urlMovies}}/1
###




POST {{host}}{{urlMovies}}/newMovie
Content-Type: application/json

{
"title": "Harry Potter and la maldicion de alberto.meme",
"year": 2023,
"image": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"

}
###
DELETE {{host}}{{urlMovies}}/10



#######Characters

GET {{host}}{{urlCharacters}}

###

GET {{host}}{{urlCharacters}}/1

###
PUT {{host}}{{urlCharacters}}/6
Content-Type: application/json

{
 "name": "Severus Snape",
  "type": "hero",
  "image": "https://media.glamour.es/photos/616f9ac038abdad04f45538b/master/w_1600%2Cc_limit/605146.jpg",
  "status": "dead"
 
}
###
POST {{host}}{{urlCharacters}}/newCharacter
Content-Type: application/json

{
"name": "Draco Malfoy",
"type": "villain",
"image": "https://noelialopezcheda.files.wordpress.com/2015/12/una-foto-promo-di-draco-malfoy-tom-felton-per-il-film-harry-potter-e-la-pietra-filosofale-129105.jpg?w=640",
"status": "alive"

}
###

DELETE {{host}}{{urlCharacters}}/10

###



#######Usuarios



###
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
"username": "admin6",
"email": "admin6@gmail.com",
"password": "admin",
"role": "admin"

}

###

POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{

"email": "admin@gmail.com",
"password": "admin"


}